package com.easytonent.common.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		// Composite Primary Key order: deviceId,uuid
		arp.addMapping("ctoken", "deviceId,uuid", Ctoken.class);
		arp.addMapping("customer", "id", Customer.class);
		arp.addMapping("driver", "id", Driver.class);
		// Composite Primary Key order: deviceId,uuid
		arp.addMapping("dtoken", "deviceId,uuid", Dtoken.class);
		// Composite Primary Key order: id,orderNo
		arp.addMapping("intention", "id,orderNo", Intention.class);
		arp.addMapping("location", "driverId", Location.class);
		arp.addMapping("orders", "id", Orders.class);
		arp.addMapping("routes", "id", Routes.class);
		arp.addMapping("user", "id", User.class);
	}
}

