package com.easytonent.common.model;

import java.util.List;

import com.easytonent.common.model.base.BaseCtoken;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Ctoken extends BaseCtoken<Ctoken> {
	public static final Ctoken dao = new Ctoken();
	public Ctoken findByUuidAndDeviceIdAndAccesstoken(String uuid, String deviceId, String accessToken) {
		return findFirst("select * from ctoken where uuid=? and deviceId=? and accessToken=?", uuid, deviceId, accessToken);
	}
	
	public Ctoken builderAccessToken(String uuid, String deviceId, String appId, String accessToken){
		Ctoken token = new Ctoken();
		token.setUuid(uuid);
		token.setDeviceId(deviceId);
		token.setAppId(appId);
		token.setAccessToken(accessToken);
		token.save();
		return token;
	}

	public Ctoken findByUuidAndDeviceId(String id, String deviceId) {
		return findFirst("select * from ctoken where uuid=? and deviceId=?", id, deviceId);
	}

	public List<Ctoken> findByUuid(String uuid) {
		return find("select * from ctoken where uuid=? ", uuid);
	}
}
