package com.easytonent.common.model;

import com.easytonent.common.model.base.BaseCustomer;
import com.jfinal.plugin.activerecord.Page;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Customer extends BaseCustomer<Customer> {
	public static final Customer dao = new Customer();
	public Page<Customer> paginate(int pageNumber, int pageSize) {
		return paginate(pageNumber, pageSize, "select *", "from customer order by created desc");
	}
	public Customer findByPhone(String phone) {
		return findFirst("select * from customer where phone=?", phone);
	}
}
