package com.easytonent.common.model;

import java.util.List;

import com.easytonent.common.model.base.BaseDriver;
import com.jfinal.plugin.activerecord.Page;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Driver extends BaseDriver<Driver> {
	public static final Driver dao = new Driver();
	public Page<Driver> paginate(int pageNumber, int pageSize) {
		return paginate(pageNumber, pageSize, "select *", "from driver order by created desc");
	}
	public Driver findByPhone(String phone) {
		return findFirst("select * from driver where phone=?", phone);
	}
	public List<Driver> findAll(String state) {
		return find("select * from driver where state=?", state);
	}
}
