package com.easytonent.common.model;

import java.util.List;

import com.easytonent.common.model.base.BaseDtoken;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Dtoken extends BaseDtoken<Dtoken> {
	public static final Dtoken dao = new Dtoken();
	public Dtoken findByUuidAndDeviceIdAndAccesstoken(String uuid, String deviceId, String accessToken) {
		return findFirst("select * from dtoken where uuid=? and deviceId=? and accessToken=?", uuid, deviceId, accessToken);
	}
	
	public Dtoken builderAccessToken(String uuid, String deviceId, String appId, String accessToken){
		Dtoken token = new Dtoken();
		token.setUuid(uuid);
		token.setDeviceId(deviceId);
		token.setAppId(appId);
		token.setAccessToken(accessToken);
		token.save();
		return token;
	}

	public Dtoken findByUuidAndDeviceId(String id, String deviceId) {
		return findFirst("select * from dtoken where uuid=? and deviceId=?", id, deviceId);
	}

	public List<Dtoken> findByUuid(String uuid) {
		return find("select * from dtoken where uuid=? ", uuid);
	}
}
