package com.easytonent.common.model;

import com.easytonent.common.model.base.BaseLocation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Location extends BaseLocation<Location> {
	public static final Location dao = new Location();
}
