package com.easytonent.common.model;

import com.easytonent.common.model.base.BaseOrders;
import com.jfinal.plugin.activerecord.Page;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Orders extends BaseOrders<Orders> {
	public static final Orders dao = new Orders();
	public Page<Orders> paginate(int pageNumber, int pageSize) {
		return paginate(pageNumber, pageSize, "select *", "from orders order by created desc");
	}
	public Page<Orders> paginateByCusomter(int pageNumber, int pageSize, String id) {
		return paginate(pageNumber, pageSize, "select o.*", "from orders o left join customer c on o.customerId=c.id where c.id=? order by o.created desc", id);
	}
	public Page<Orders> paginateByDriver(int pageNumber, int pageSize, String id) {
		return paginate(pageNumber, pageSize, "select o.*", "from orders o left join driver d on o.customerId=d.id where d.id=? order by o.created desc", id);
	}
	
	public Orders findByOrderNo(String orderNo){
		return findFirst("select * from orders where orderNo=?", orderNo);
	}
	public Orders findByCustomer(String uuid, String status1, String status2, String status3) {
		return findFirst("select * from orders where customerId=? and (status=? or status=? or status=?)", uuid, status1, status2, status3);
	}
	
}
