package com.easytonent.common.model;

import java.util.List;

import com.easytonent.common.model.base.BaseRoutes;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Routes extends BaseRoutes<Routes> {
	public static final Routes dao = new Routes();

	public List<Routes> findByOrderNo(String orderNo) {
		return find("select r.loc from routes r where r.orderNo=? order by r.created asc", orderNo);
	}
}
