package com.smartwork.common.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseContacts<M extends BaseContacts<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setDept(java.lang.Integer dept) {
		set("dept", dept);
	}

	public java.lang.Integer getDept() {
		return get("dept");
	}

	public void setJobs(java.lang.Integer jobs) {
		set("jobs", jobs);
	}

	public java.lang.Integer getJobs() {
		return get("jobs");
	}

	public void setNamecn(java.lang.String namecn) {
		set("namecn", namecn);
	}

	public java.lang.String getNamecn() {
		return get("namecn");
	}

	public void setNameen(java.lang.String nameen) {
		set("nameen", nameen);
	}

	public java.lang.String getNameen() {
		return get("nameen");
	}

	public void setPhone(java.lang.String phone) {
		set("phone", phone);
	}

	public java.lang.String getPhone() {
		return get("phone");
	}

	public void setPwd(java.lang.String pwd) {
		set("pwd", pwd);
	}

	public java.lang.String getPwd() {
		return get("pwd");
	}

	public void setEmail(java.lang.String email) {
		set("email", email);
	}

	public java.lang.String getEmail() {
		return get("email");
	}

	public void setCreated(java.util.Date created) {
		set("created", created);
	}

	public java.util.Date getCreated() {
		return get("created");
	}

}
