package com.easytonent.common.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCustomer<M extends BaseCustomer<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setImg(java.lang.String img) {
		set("img", img);
	}

	public java.lang.String getImg() {
		return get("img");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setPhone(java.lang.String phone) {
		set("phone", phone);
	}

	public java.lang.String getPhone() {
		return get("phone");
	}

	public void setCarAge(java.lang.Integer carAge) {
		set("carAge", carAge);
	}

	public java.lang.Integer getCarAge() {
		return get("carAge");
	}

	public void setGears(java.lang.String gears) {
		set("gears", gears);
	}

	public java.lang.String getGears() {
		return get("gears");
	}

	public void setUrgentContacts(java.lang.String urgentContacts) {
		set("urgentContacts", urgentContacts);
	}

	public java.lang.String getUrgentContacts() {
		return get("urgentContacts");
	}

	public void setCreated(java.util.Date created) {
		set("created", created);
	}

	public java.util.Date getCreated() {
		return get("created");
	}

}
