package com.easytonent.common.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDriver<M extends BaseDriver<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setImg(java.lang.String img) {
		set("img", img);
	}

	public java.lang.String getImg() {
		return get("img");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setIdNumber(java.lang.String idNumber) {
		set("idNumber", idNumber);
	}

	public java.lang.String getIdNumber() {
		return get("idNumber");
	}

	public void setPhone(java.lang.String phone) {
		set("phone", phone);
	}

	public java.lang.String getPhone() {
		return get("phone");
	}

	public void setDateLicense(java.lang.String dateLicense) {
		set("dateLicense", dateLicense);
	}

	public java.lang.String getDateLicense() {
		return get("dateLicense");
	}

	public void setImgLicense(java.lang.String imgLicense) {
		set("imgLicense", imgLicense);
	}

	public java.lang.String getImgLicense() {
		return get("imgLicense");
	}

	public void setImgIdNumber(java.lang.String imgIdNumber) {
		set("imgIdNumber", imgIdNumber);
	}

	public java.lang.String getImgIdNumber() {
		return get("imgIdNumber");
	}

	public void setState(java.lang.String state) {
		set("state", state);
	}

	public java.lang.String getState() {
		return get("state");
	}

	public void setStatus(java.lang.String status) {
		set("status", status);
	}

	public java.lang.String getStatus() {
		return get("status");
	}

	public void setCreated(java.util.Date created) {
		set("created", created);
	}

	public java.util.Date getCreated() {
		return get("created");
	}

}
