package com.easytonent.common.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseIntention<M extends BaseIntention<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setOrderNo(java.lang.String orderNo) {
		set("orderNo", orderNo);
	}

	public java.lang.String getOrderNo() {
		return get("orderNo");
	}

	public void setFromloc(java.lang.String fromloc) {
		set("fromloc", fromloc);
	}

	public java.lang.String getFromloc() {
		return get("fromloc");
	}

	public void setToloc(java.lang.String toloc) {
		set("toloc", toloc);
	}

	public java.lang.String getToloc() {
		return get("toloc");
	}

	public void setPrice(java.math.BigDecimal price) {
		set("price", price);
	}

	public java.math.BigDecimal getPrice() {
		return get("price");
	}

	public void setDistance(java.lang.Double distance) {
		set("distance", distance);
	}

	public java.lang.Double getDistance() {
		return get("distance");
	}

	public void setTime(java.lang.String time) {
		set("time", time);
	}

	public java.lang.String getTime() {
		return get("time");
	}

	public void setState(java.lang.String state) {
		set("state", state);
	}

	public java.lang.String getState() {
		return get("state");
	}

}
