package com.easytonent.common.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOrders<M extends BaseOrders<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setOrderNo(java.lang.String orderNo) {
		set("orderNo", orderNo);
	}

	public java.lang.String getOrderNo() {
		return get("orderNo");
	}

	public void setFromloc(java.lang.String fromloc) {
		set("fromloc", fromloc);
	}

	public java.lang.String getFromloc() {
		return get("fromloc");
	}

	public void setFromlat(java.lang.String fromlat) {
		set("fromlat", fromlat);
	}

	public java.lang.String getFromlat() {
		return get("fromlat");
	}

	public void setFromlng(java.lang.String fromlng) {
		set("fromlng", fromlng);
	}

	public java.lang.String getFromlng() {
		return get("fromlng");
	}

	public void setToloc(java.lang.String toloc) {
		set("toloc", toloc);
	}

	public java.lang.String getToloc() {
		return get("toloc");
	}

	public void setTolat(java.lang.String tolat) {
		set("tolat", tolat);
	}

	public java.lang.String getTolat() {
		return get("tolat");
	}

	public void setTolng(java.lang.String tolng) {
		set("tolng", tolng);
	}

	public java.lang.String getTolng() {
		return get("tolng");
	}

	public void setTime(java.lang.String time) {
		set("time", time);
	}

	public java.lang.String getTime() {
		return get("time");
	}

	public void setPrice(java.math.BigDecimal price) {
		set("price", price);
	}

	public java.math.BigDecimal getPrice() {
		return get("price");
	}

	public void setState(java.lang.String state) {
		set("state", state);
	}

	public java.lang.String getState() {
		return get("state");
	}

	public void setStatus(java.lang.String status) {
		set("status", status);
	}

	public java.lang.String getStatus() {
		return get("status");
	}

	public void setTimes(java.lang.Integer times) {
		set("times", times);
	}

	public java.lang.Integer getTimes() {
		return get("times");
	}

	public void setDriverId(java.lang.String driverId) {
		set("driverId", driverId);
	}

	public java.lang.String getDriverId() {
		return get("driverId");
	}

	public void setCustomerId(java.lang.String customerId) {
		set("customerId", customerId);
	}

	public java.lang.String getCustomerId() {
		return get("customerId");
	}

	public void setContact(java.lang.String contact) {
		set("contact", contact);
	}

	public java.lang.String getContact() {
		return get("contact");
	}

	public void setRoutes(java.lang.String routes) {
		set("routes", routes);
	}

	public java.lang.String getRoutes() {
		return get("routes");
	}

	public void setCreated(java.util.Date created) {
		set("created", created);
	}

	public java.util.Date getCreated() {
		return get("created");
	}

}
