package com.easytonent.common.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDtoken<M extends BaseDtoken<M>> extends Model<M> implements IBean {

	public void setUuid(java.lang.String uuid) {
		set("uuid", uuid);
	}

	public java.lang.String getUuid() {
		return get("uuid");
	}

	public void setDeviceId(java.lang.String deviceId) {
		set("deviceId", deviceId);
	}

	public java.lang.String getDeviceId() {
		return get("deviceId");
	}

	public void setAppId(java.lang.String appId) {
		set("appId", appId);
	}

	public java.lang.String getAppId() {
		return get("appId");
	}

	public void setAccessToken(java.lang.String accessToken) {
		set("accessToken", accessToken);
	}

	public java.lang.String getAccessToken() {
		return get("accessToken");
	}

}
