package com.easytonent.common.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRoutes<M extends BaseRoutes<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setOrderNo(java.lang.String orderNo) {
		set("orderNo", orderNo);
	}

	public java.lang.String getOrderNo() {
		return get("orderNo");
	}

	public void setLoc(java.lang.String loc) {
		set("loc", loc);
	}

	public java.lang.String getLoc() {
		return get("loc");
	}

	public void setCreated(java.util.Date created) {
		set("created", created);
	}

	public java.util.Date getCreated() {
		return get("created");
	}

}
