package com.smartwork.common.model;

import java.util.List;

import com.jfinal.plugin.activerecord.Page;
import com.smartwork.common.model.base.BaseContacts;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Contacts extends BaseContacts<Contacts> {
	public static final Contacts dao = new Contacts();

	public Page<Contacts> paginate(int pageNumber, int pageSize){
		return paginate(pageNumber, pageSize, "select * ", "from contacts group by dept,jobs,phone order by created desc");
	}
	
	public Contacts login(String phone, String pwd) {
		return findFirst("select * from contacts where phone=? and pwd=?", phone, pwd);
	}

	public List<Contacts> findAll() {
		return find("select * from contacts group by dept,jobs,phone order by created desc");
	}

	public Contacts checkPhone(String phone) {
		return findFirst("select * from contacts where phone=?", phone);
	}
}
